### ISSUE TITLE
El maquetador puja l’article al sistema web

### ISSUE THREAD

**Issue by ferranmartinezlleida** [GR5-Join-Project/El_Juernes#56]
Com a maquetador vull pujar l’article al sistema web per publicar-lo.

**Comment by ricardzm** [comment]
* Curt = menys de 100 paraules
* Mig = 100 i 400 paraules
* Llarg = més de 400 paraules

Tenir en compte la API de bannes: http://enigmatic-waters-71955.herokuapp.com/api/images
